version: 2

dvd_rentals:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: root
      port: 5432
      dbname: dvdrental
      schema: public
      threads: 4